spring:
  application:
    name: yooncheolCommunity
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create               # ??? ?? ?? ???? (MyBatis ?? ?)
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always

server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: kr.co.yooncheolcommunity.api.*.dto, kr.co.yooncheolcommunity.api.*.entity
  config-location: classpath:mybatis-config.xml
